function regions = lorentzian_regions()
%LORENTZIAN_REGIONS Configuration for Lorentzian fitting windows.
%   Edit this file to specify which spectra (.spe files) to fit and what
%   fitting windows to use. Each entry declares the fitting center, window
%   width (half-window, in cm^-1), and initial peak centers.
%
%   Example below assumes dazo3.spe contains 11 peaks inside a 60 cm^-1
%   window around 1600 cm^-1. Adjust centers and windows to match your data.
%   Use Caliblation(x) to convert pixel indices to wavenumbers if you prefer
%   to reason about the regions in pixel space.

regions = struct('spectrum', {}, 'center_cm1', {}, 'window_cm1', {}, ...
                 'peak_centers_cm1', {}, 'initial_amplitude', {}, 'initial_gamma_cm1', {});

regions(end + 1) = struct( ...
    'spectrum', 'dazo3.spe', ...
    'center_cm1', 1600, ...
    'window_cm1', 60, ...
    'peak_centers_cm1', 1600 + linspace(-30, 30, 11), ...
    'initial_amplitude', ones(1, 11), ...
    'initial_gamma_cm1', repmat(5, 1, 11));

% Add more spectra below following the same pattern.
% regions(end + 1) = struct( ...
%     'spectrum', 'example.spe', ...
%     'center_cm1', 1400, ...
%     'window_cm1', 40, ...
%     'peak_centers_cm1', [1380, 1395, 1408], ...
%     'initial_amplitude', [1, 1, 1], ...
%     'initial_gamma_cm1', [4, 4, 4]);

end
